### ISSUE TITLE
multi-statusbar

### ISSUE THREAD

**Issue by AprLie** [gpakosz/.tmux#353]
When I connect to remote sever, the statusbar gradually stacks. If I detach the tmux server and attach again, this problem still exists. Do you have ideas about this problem?
![image](https://user-images.githubusercontent.com/40601864/82047662-c715e700-96e5-11ea-924a-0cbea8395aba.png)

**Comment by gpakosz** [comment]
Hello @AprLie 👋

This is covered in https://github.com/gpakosz/.tmux#troubleshooting

Either adjust your terminal emulator settings about Unicode characters width or stop using emojis in your status line.

**Comment by AprLie** [comment]
> Hello @AprLie 👋
> 
> This is covered in https://github.com/gpakosz/.tmux#troubleshooting
> 
> Either adjust your terminal emulator settings about Unicode characters width or stop using emojis in your status line.

How can I stop using emojis in my status line?

**Comment by gpakosz** [comment]
Edit your ~`/.tmux.conf.local` copy them reload the configuration.

Typically, the default value for `tmux_conf_theme_pairing` is still using an emoji.
Changing it to something else or to the empty string should solve the problem.

**Comment by AprLie** [comment]
Thank you for your answer, another problem is that I cannot use the mouse and pageup bottom to copy multi-pages output on the screen, or I cannot use the space bottom to select the output in vim mode. Could you give me a solution?

**Comment by gpakosz** [comment]
I suggest you get familiar with tmux itself. Look for copy mode and mouse mode in the manual.

**Comment by thegregyang** [comment]
Hi, I have the same problem with windows terminal. I updated all the packages in the troubleshooting page and also set the locale to UTF-8. However, this multi-line behavior still occurs, most notably when I do `ctrl-a ctrl-h` or `ctrl-a ctrl-l` really fast. Is this a known problem?

**Comment by thegregyang** [comment]
Actually, I just realized that this only occurs with `ctrl-a ctrl-l`. Do you know why this happens?

**Comment by thegregyang** [comment]
I just tried MobaXterm on windows, and this problem doesn't occur there, so seems like only a windows terminal issue.

**Comment by gpakosz** [comment]
See #355. Try to upgrade Windows Terminal

**Comment by thegregyang** [comment]
Thanks @gpakosz, updating to windows terminal 1.0 solved the issue for me.

**Comment by owenstake** [comment]
In Xshell, I fix it by set `CJKAmbiAsWide=0` in terminal setting.
