### ISSUE TITLE
unable to minimize after upgrading tmux

### ISSUE THREAD

**Issue by avshyz** [gpakosz/.tmux#381]
Hi!
I've upgraded my tmux to "tmux next-3.3" today, and I've encountered the following issue:
When I try to maximize a pane, everything works, but when I try to minimize it I'm prompted with 
"Can't maximize with only one pane"

**Comment by gpakosz** [comment]
Hello @avshyz 👋

Thanks for the report, I'll look into it.

**Comment by gpakosz** [comment]
Hey @avshyz 👋

Can you please give the `gh-381` branch a try? It should fix it.

**Comment by baileywickham** [comment]
Hey @gpakosz 
I had the same issue also running tmux next-3.3. This branch fixed it. There is a slight (< 50ms) lag between when C-+ is hit and when the pane is maximized, flashing a "pane is dead message", but this isn't a problem.

**Comment by gpakosz** [comment]
Hey @baileywickham 👋

Thanks for testing!
I pushed another commit. Can you see if you still experience the lag?

**Comment by baileywickham** [comment]
Using the newest commit I still experience the lag. It is <50ms so it isn't a huge deal.

I installed tmux3.0a from the apt repo and I am experiencing the same lag there, though using the latest commits I am unable to un-maximize back to two panes on 3.0a.

**Comment by gpakosz** [comment]
I don't experience a lag. Or at least I can't see it 😅

I'm wondering whether it's due to the fact that I'm printing empty lines so that the `Pane has been maximized...` message is visible.

Can you please try the latest commit?

**Comment by baileywickham** [comment]
Huh, that's odd. I am running the lastest gh-381 branch with tmux 3.3-next built from source. 

The latest commit didn't fix it for me. I attached a gif of what I am seeing. 
![Peek 2020-09-28 16-49](https://user-images.githubusercontent.com/22156662/94496962-ac32a380-01aa-11eb-967e-ad0e65ae3565.gif)

**Comment by gpakosz** [comment]
Hey @baileywickham 

Not sure what's happening. Do you see the same if the window is larger?

Also I committed yet another version which is supposed to reduce the time it takes for the placeholder pane enter the dead state.

**Comment by baileywickham** [comment]
Hi @gpakosz 

First of all, thanks for the amount of effort you are putting in to solve this! 

The lag is the same with the latest commit. The lag is also the same no matter the window size. It may be related to my shell or other environmental factors, not tmux.  

@avshyz Are you experiencing the same lag?

**Comment by gpakosz** [comment]
Hey @baileywickham 

> It may be related to my shell or other environmental factors, not tmux.

That's what I find intriguing: tmux is supposed to launch commands through `/bin/sh -c 'command'`. It may depend on whether `/bin/sh` is a symlink to e.g. `zsh` on your system and what's going on when your shell initializes

**Comment by baileywickham** [comment]
`/bin/sh` isn't a symlink on my machine and testing it with my default shell as `sh` didn't fix it either. Probably not worth worrying about unless someone else also has the same problem. I'm not sure what else it could be.

**Comment by gpakosz** [comment]
Ok let's merge the fix

**Comment by baileywickham** [comment]
Great, thanks!
